package event;

/**
 * @author Robert Engle
 *
 * A class descibing the types of events that can occur from either the log file or the RCON console.
 */
public enum EventType {
    //Log file
    ADMIN_BROADCAST,DEPLOYABLE_DAMAGED,NEW_GAME,PLAYER_CONNECTED,PLAYER_DAMAGED,PLAYER_DIED,PLAYER_DISCONNECTED,
    PLAYER_POSSESS,PLAYER_REVIVED,PLAYER_UNPOSSESS,PLAYER_WOUNDED,ROUND_WINNER,SERVER_TICK_RATE,SQUAD_CREATED,
    STEAMID_CONNECTED,

    //RCON
    CHAT_MESSAGE,PLAYER_BANNED,PLAYER_WARNED,PLAYER_KICKED,POSSESSED_ADMIN_CAM,UNPOSSESSED_ADMIN_CAM,PLAYERLIST_UPDATED,
    SQUADLIST_UPDATED, LAYERINFO_UPDATED,

    //A2S
    A2S_UPDATED
}
